const prmHandle_type prmh[] = {
	// Target
	{
		.prm = (prmval_type*)&prmData.version_major,
		.def.t_u16Frmt= 0 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "version_major",
		.units = "",
		.pCallback = getFwVer,
		.addr = 0x0000,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.version_minor,
		.def.t_u16Frmt= 0 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "version_minor",
		.units = "",
		.pCallback = getFwVer,
		.addr = 0x0001,
		.parameter = 1,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.version_revision,
		.def.t_u16Frmt= 0 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "version_revision",
		.units = "",
		.pCallback = getFwVer,
		.addr = 0x0002,
		.parameter = 2,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.version_build,
		.def.t_u16Frmt= 0 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "version_build",
		.units = "",
		.pCallback = getFwVer,
		.addr = 0x0003,
		.parameter = 3,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.bodbus_address,
		.def.t_u16Frmt= 1 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "bodbus_address",
		.units = "",
		.pCallback = NULL,
		.addr = 0x0004,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},

	// Target
	{
		.prm = (prmval_type*)&prmData.voltage_set,
		.def.t_u32Frmt= 0.0000 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 36.0000 * power6,
		.label = "voltage_set",
		.units = "V",
		.pCallback = NULL,
		.addr = 0x0100,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.current_set,
		.def.t_u32Frmt= 0.00000 * power6,
		.min.t_u32Frmt= 0.00000 * power6,
		.max.t_u32Frmt= 4.00000 * power6,
		.label = "current_set",
		.units = "A",
		.pCallback = NULL,
		.addr = 0x0102,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.vdac,
		.def.t_u16Frmt= 0 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 4095 * power0,
		.label = "vdac",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0104,
		.parameter = 1,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.idac,
		.def.t_u16Frmt= 0 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 4095 * power0,
		.label = "idac",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0105,
		.parameter = 1,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.mode,
		.def.t_u16Frmt= 0 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 4 * power0,
		.label = "mode",
		.units = "",
		.pCallback = NULL,
		.addr = 0x0106,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.time_set,
		.def.t_u32Frmt= 0 * power0,
		.min.t_u32Frmt= 0 * power0,
		.max.t_u32Frmt= 999000 * power0,
		.label = "time_set",
		.units = "s",
		.pCallback = NULL,
		.addr = 0x0107,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.enable,
		.def.t_boolFrmt= 0 * power0,
		.min.t_boolFrmt= 0 * power0,
		.max.t_boolFrmt= 1 * power0,
		.label = "enable",
		.units = "",
		.pCallback = NULL,
		.addr = 0x0109,
		.parameter = 0,
		.type = boolFrmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmNotSave,
	},

	// Measurement
	{
		.prm = (prmval_type*)&prmData.voltage,
		.def.t_u32Frmt= 0.0000 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 36.0000 * power6,
		.label = "voltage",
		.units = "V",
		.pCallback = NULL,
		.addr = 0x0200,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodR,
		.power = 6,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.current,
		.def.t_u32Frmt= 0.00000 * power6,
		.min.t_u32Frmt= 0.00000 * power6,
		.max.t_u32Frmt= 4.00000 * power6,
		.label = "current",
		.units = "A",
		.pCallback = NULL,
		.addr = 0x0202,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodR,
		.power = 6,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.power,
		.def.t_u32Frmt= 0.000 * power3,
		.min.t_u32Frmt= 0.000 * power3,
		.max.t_u32Frmt= 160.000 * power3,
		.label = "power",
		.units = "W",
		.pCallback = NULL,
		.addr = 0x0204,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodR,
		.power = 3,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.resistance,
		.def.t_u32Frmt= 0.000 * power3,
		.min.t_u32Frmt= 0.000 * power3,
		.max.t_u32Frmt= 999.000 * power3,
		.label = "resistance",
		.units = "Ohm",
		.pCallback = NULL,
		.addr = 0x0206,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodR,
		.power = 3,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.time,
		.def.t_u32Frmt= 0 * power0,
		.min.t_u32Frmt= 0 * power0,
		.max.t_u32Frmt= 999000 * power0,
		.label = "time",
		.units = "s",
		.pCallback = NULL,
		.addr = 0x0208,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodR,
		.power = 0,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.capacity,
		.def.t_u32Frmt= 0 * power3,
		.min.t_u32Frmt= 0 * power3,
		.max.t_u32Frmt= 999.000 * power3,
		.label = "capacity",
		.units = "Ah",
		.pCallback = NULL,
		.addr = 0x020A,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodR,
		.power = 3,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.input_voltage,
		.def.t_u32Frmt= 0.000 * power6,
		.min.t_u32Frmt= 0.000 * power6,
		.max.t_u32Frmt= 100.000 * power6,
		.label = "input_voltage",
		.units = "V",
		.pCallback = NULL,
		.addr = 0x020C,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodR,
		.power = 6,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.temperature,
		.def.t_u16Frmt= 0.0 * power1,
		.min.t_u16Frmt= 0.0 * power1,
		.max.t_u16Frmt= 125.0 * power1,
		.label = "temperature",
		.units = "°С",
		.pCallback = NULL,
		.addr = 0x020E,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodR,
		.power = 1,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.state,
		.def.t_u16Frmt= 0 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "state",
		.units = "",
		.pCallback = NULL,
		.addr = 0x020F,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodR,
		.power = 0,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.vadc,
		.def.t_u16Frmt= 0 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "vadc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0210,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodR,
		.power = 0,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.iadc,
		.def.t_u16Frmt= 0 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "iadc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0211,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodR,
		.power = 0,
		.save = prmNotSave,
	},
	{
		.prm = (prmval_type*)&prmData.iexternaladc,
		.def.t_s16Frmt= 0 * power0,
		.min.t_s16Frmt= -32768 * power0,
		.max.t_s16Frmt= 32767 * power0,
		.label = "iexternaladc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0212,
		.parameter = 0,
		.type = s16Frmt,
		.chmod = chmodR,
		.power = 0,
		.save = prmNotSave,
	},

	// calibration
	{
		.prm = (prmval_type*)&prmData.v0_u,
		.def.t_u32Frmt= 0.0101 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 36.0000 * power6,
		.label = "v0_u",
		.units = "V",
		.pCallback = vsave,
		.addr = 0x0500,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.v1_u,
		.def.t_u32Frmt= 0.1050 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 36.0000 * power6,
		.label = "v1_u",
		.units = "V",
		.pCallback = vsave,
		.addr = 0x0502,
		.parameter = 1,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.v2_u,
		.def.t_u32Frmt= 19.0000 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 36.0000 * power6,
		.label = "v2_u",
		.units = "V",
		.pCallback = vsave,
		.addr = 0x0504,
		.parameter = 2,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.v3_u,
		.def.t_u32Frmt= 30.0000 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 36.0000 * power6,
		.label = "v3_u",
		.units = "V",
		.pCallback = vsave,
		.addr = 0x0506,
		.parameter = 3,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.i0_i,
		.def.t_u32Frmt= 0.00966 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 4.00000 * power6,
		.label = "i0_i",
		.units = "A",
		.pCallback = isave,
		.addr = 0x0600,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.i1_i,
		.def.t_u32Frmt= 0.01007 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 4.00000 * power6,
		.label = "i1_i",
		.units = "A",
		.pCallback = isave,
		.addr = 0x0602,
		.parameter = 1,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.i2_i,
		.def.t_u32Frmt= 1.50000 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 4.00000 * power6,
		.label = "i2_i",
		.units = "A",
		.pCallback = isave,
		.addr = 0x0604,
		.parameter = 2,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.i3_i,
		.def.t_u32Frmt= 3.00000 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 4.00000 * power6,
		.label = "i3_i",
		.units = "A",
		.pCallback = isave,
		.addr = 0x0606,
		.parameter = 3,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmSaveSys,
	},

	// calibration
	{
		.prm = (prmval_type*)&prmData.iext0_i,
		.def.t_u32Frmt= 0.00966 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 4.00000 * power6,
		.label = "iext0_i",
		.units = "A",
		.pCallback = NULL,
		.addr = 0x0700,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.iext1_i,
		.def.t_u32Frmt= 0.01007 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 4.00000 * power6,
		.label = "iext1_i",
		.units = "A",
		.pCallback = NULL,
		.addr = 0x0702,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.iext2_i,
		.def.t_u32Frmt= 1.50000 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 4.00000 * power6,
		.label = "iext2_i",
		.units = "A",
		.pCallback = NULL,
		.addr = 0x0704,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.iext3_i,
		.def.t_u32Frmt= 3.00000 * power6,
		.min.t_u32Frmt= 0.0000 * power6,
		.max.t_u32Frmt= 4.00000 * power6,
		.label = "iext3_i",
		.units = "A",
		.pCallback = NULL,
		.addr = 0x0706,
		.parameter = 0,
		.type = u32Frmt,
		.chmod = chmodRW,
		.power = 6,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.v0_adc,
		.def.t_u16Frmt= 414 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "v0_adc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0800,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.v1_adc,
		.def.t_u16Frmt= 580 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "v1_adc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0801,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.v2_adc,
		.def.t_u16Frmt= 33230 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "v2_adc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0802,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.v3_adc,
		.def.t_u16Frmt= 52292 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "v3_adc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0803,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.v0_dac,
		.def.t_u16Frmt= 25 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "v0_dac",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0804,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.v1_dac,
		.def.t_u16Frmt= 35 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "v1_dac",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0805,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.v2_dac,
		.def.t_u16Frmt= 2021 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "v2_dac",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0806,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.v3_dac,
		.def.t_u16Frmt= 3178 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "v3_dac",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0507,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.i0_adc,
		.def.t_u16Frmt= 562 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "i0_adc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0808,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.i1_adc,
		.def.t_u16Frmt= 1980 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "i1_adc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0809,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.i2_adc,
		.def.t_u16Frmt= 24539 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "i2_adc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x080A,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.i3_adc,
		.def.t_u16Frmt= 48647 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "i3_adc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x080B,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.i0_dac,
		.def.t_u16Frmt= 35 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "i0_dac",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x080C,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.i1_dac,
		.def.t_u16Frmt= 121 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "i1_dac",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x080D,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.i2_dac,
		.def.t_u16Frmt= 1491 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "i2_dac",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x080E,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.i3_dac,
		.def.t_u16Frmt= 2958 * power0,
		.min.t_u16Frmt= 0 * power0,
		.max.t_u16Frmt= 65535 * power0,
		.label = "i3_dac",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x080F,
		.parameter = 0,
		.type = u16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.iext0_adc,
		.def.t_s16Frmt= 50 * power0,
		.min.t_s16Frmt= 0 * power0,
		.max.t_s16Frmt= 65535 * power0,
		.label = "iext0_adc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0810,
		.parameter = 0,
		.type = s16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.iext1_adc,
		.def.t_s16Frmt= 340 * power0,
		.min.t_s16Frmt= 0 * power0,
		.max.t_s16Frmt= 65535 * power0,
		.label = "iext1_adc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0811,
		.parameter = 0,
		.type = s16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.iext2_adc,
		.def.t_s16Frmt= 3214 * power0,
		.min.t_s16Frmt= 0 * power0,
		.max.t_s16Frmt= 65535 * power0,
		.label = "iext2_adc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0812,
		.parameter = 0,
		.type = s16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
	{
		.prm = (prmval_type*)&prmData.iext3_adc,
		.def.t_s16Frmt= 32767 * power0,
		.min.t_s16Frmt= 0 * power0,
		.max.t_s16Frmt= 65535 * power0,
		.label = "iext3_adc",
		.units = "lsb",
		.pCallback = NULL,
		.addr = 0x0813,
		.parameter = 0,
		.type = s16Frmt,
		.chmod = chmodRW,
		.power = 0,
		.save = prmSaveSys,
	},
};
